FROM openjdk
WORKDIR usr/src
ADD ./target/playerrecommendationservice-2.2.5.RELEASE.jar /usr/src/playerrecommendationservice-2.2.5.RELEASE.jar
ENTRYPOINT ["java","-jar","playerrecommendationservice-2.2.5.RELEASE.jar"]